#!/bin/bash
#SBATCH --job-name=GRID_TEMPLATE
#SBATCH --account=plgar2026-cpu     # hpc-grants -> Allocation:
#SBATCH --partition=cpu-lowprio          # sinfo -s   -> Partition:   cpu | cpu-lowprio | plgrid
#SBATCH --time=02:00:00
#SBATCH --ntasks=8
#SBATCH --cpus-per-task=1
#SBATCH --mem=16G
#SBATCH --output=output/out_%j.txt
#SBATCH --error=output/err_%j.txt

source "$(dirname "$0")/_common_"
#--account=plgar2026-cpu     # hpc-grants -> Allocation:
#--partition=cpu             # sinfo -s   -> Partition:

## GPU #
##SBATCH --gres=gpu:1

cd $SLURM_SUBMIT_DIR
ls -al

# Load modules #
module load openmpi/4.1.6-gcc-13.2.0
# module load cuda

# SCRATCH env activate #
# scratch_activation_path="$(realpath .)/.venv/bin/activate"
# echo "SOURCING -> $scratch_activation_path"
# source $scratch_activation_path



# START #
echo "GRID_JOB -> STARTED"

    # srun uv run _src/main.py
    # mpirun -np $SLURM_NTASKS python _src/main.py
    # srun --ntasks=1 .venv/bin/mpirun -np $SLURM_NTASKS uv run _src/main.py

    mpirun -np $SLURM_NTASKS uv run python _src/main.py


echo "GRID_JOB -> ENDED"
