#!/bin/bash
#SBATCH --job-name=GRID_TEMPLATE
#SBATCH --account=plglscclass26-gpu
#SBATCH --partition=plgrid-gpu-v100
#SBATCH --time=02:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=16G
#SBATCH --gres=gpu:1
#SBATCH --output=GRID_log_out_%j.txt
#SBATCH --error=GRID_log_err_%j.txt

cd $SLURM_SUBMIT_DIR
ls -al

# Load modules #
module load openmpi/4.1.6-gcc-13.2.0
# module load cuda

# SCRATCH env activate #
scratch_activation_path="$(realpath .)/.venv/bin/activate"
echo "SOURCING -> $scratch_activation_path"
source $scratch_activation_path



# START #
echo "GRID_JOB -> STARTED"

    uv run _src/main.py

echo "GRID_JOB -> ENDED"
