#!/bin/bash
#SBATCH --job-name=GRID_test
#SBATCH --account=plglscclass26-gpu
#SBATCH --partition=plgrid-gpu-v100
#SBATCH --time=02:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=16G
#SBATCH --gres=gpu:1
#SBATCH --output=GRID_log_out_%j.txt
#SBATCH --error=GRID_log_err_%j.txt

cd $SLURM_SUBMIT_DIR
ls -al

module load python/3.12.3-gcccore-13.3.0
# Biblioteki CUDA w LD_LIBRARY_PATH — bez tego torch.cuda.is_available() często zostaje False mimo GPU w Slurm.
module load cuda

# SCRATCH env activate
pelna_sciezka=$(realpath .)
output="${pelna_sciezka#/net/people/plgrid/plgwmackowiak/}"

scratch_activation_path="$SCRATCH/$output/.venv/bin/activate"
echo "SOURCING -> $scratch_activation_path"

source $scratch_activation_path


# START #
echo "Zaczynamy trening na GPU..."
nvidia-smi || true
python train_expert_sac_her_fetch.py --check-device

python train_expert_sac_her_fetch.py
echo "Koniec zadania."
